---
- name: Update Red Hat and Fedora
  hosts: "{{ my_hosts | default ('localhost') }}"
  become: false
  remote_user: ansible
  gather_facts: false
  order: sorted
  
  roles:
    - role: savvyaxl.update_os 
    #- role: savvyaxl.email
