---
- name: update windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: update
      become: true
      become_method: runas
      become_user: SYSTEM
      ansible.windows.win_updates:
        category_names: '*'
        reject_list:
        - Lenovo - Input - USB Enhanced Performance Keyboard
        reboot: false
      failed_when: false