---
- name: Update Red Hat and Fedora
  hosts: "{{ my_hosts | default ('localhost') }}"
  become: false
  remote_user: ansible
  gather_facts: false
  order: sorted
  
  roles:
    - role: savvyaxl.update_linux
      when: false
    #- role: savvyaxl.email


- name: Update Windows
  hosts: "{{ my_win_hosts | default ('windows') }}"
  
  roles:
    - role: savvyaxl.update_windows
