---
- name: create temp directory
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  pre_tasks:
    - name: delete directory
      ansible.builtin.file:
        path: "{{temp_dir}}"
        state: absent

    - name: create directory
      ansible.builtin.file:
        path: "{{temp_dir}}"
        state: directory

    - name: get the start time
      register: time_start
      shell: date

    - name: write start time to file
      ansible.builtin.lineinfile:
        line: "time_start_site: \"{{time_start.stdout}}\""
        path: "{{temp_file}}"
        create: true

  # post_tasks:
  #   - name: get the end time
  #     register: time_end
  #     shell: date

  #   - name: write end time to file
  #     ansible.builtin.lineinfile:
  #       line: "time_end: {{time_end.stdout}}"
  #       path: "{{temp_file}}"
  #       create: true

  #   - name: email the results

  #   - name: delete files
  #     when: temp_dir is defined
  #     file:
  #       path: "{{temp_dir}}"
  #       state: absent

- name: update windows
  ansible.builtin.import_playbook: update_windows.yml

- name: update linux
  ansible.builtin.import_playbook: update_linux.yml

- name: send email
  ansible.builtin.import_playbook: update_email.yml


