---
- name: create temp directory
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  pre_tasks:
    - name: delete directory
      ansible.builtin.file:
        path: "{{temp_dir}}"
        state: absent

    - name: create directory
      ansible.builtin.file:
        path: "{{temp_dir}}"
        state: directory

    - name: get the start time
      register: time_start
      shell: date

    - name: write start time to file
      ansible.builtin.lineinfile:
        line: "<p>Start: {{time_start.stdout}}</p>"
        path: "{{temp_file}}"
        create: true

- name: update windows
  vars:
    temp_dir: /tmp/hsuteo_email
  ansible.builtin.import_playbook: update_windows.yml

- name: update linux
  vars:
    temp_dir: /tmp/hsuteo_email
  ansible.builtin.import_playbook: update_linux.yml

- name: send email
  vars:
    temp_dir: /tmp/hsuteo_email
    temp_file: "/tmp/hsuteo_email/file"
    mail_body_file: "/tmp/hsuteo_email/email_body.html"
    subject_name: System Update for Linux and Windows
  ansible.builtin.import_playbook: update_email.yml

- name: cleanup
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    ansible.builtin.file:
      path: "{{temp_dir}}"
      state: absent
