---
- name: Update Windows
  hosts: "{{ my_win_hosts | default ('windows') }}"
  gather_facts: false
  serial: 1
  vars:
    myhosts: windows
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  pre_tasks:
    - name: get the start time
      delegate_to: localhost
      register: time_start_windows
      shell: date

    - name: write role start time to file
      run_once: true
      delegate_to: localhost
      ansible.builtin.lineinfile:
        line: "time_start_windows: \"{{time_start_windows.stdout}}\""
        path: "{{temp_file}}"
        create: true

    - name: write hostname to my vars file
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "{{temp_file}}"
        line: "{{inventory_hostname}}"

  post_tasks:
    - name: get the end time
      delegate_to: localhost
      register: time_end_windows
      shell: date

    - name: write end time to file
      delegate_to: localhost
      run_once: true
      ansible.builtin.lineinfile:
        line: "time_end_windows: \"{{time_end_windows.stdout}}\""
        path: "{{temp_file}}"

    - name: Use j2 template to create individual body part
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_windows/templates/body.j2
        dest: "/{{temp_dir}}/body.{{inventory_hostname}}.html"

  roles:
    - role: savvyaxl.update_windows

