---
- name: Update Windows
  hosts: localhost
  gather_facts: false
  vars:
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  pre_tasks:
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      ansible.builtin.include_vars:
        file: "{{temp_file}}"
        name: email_stuff

  roles:
    - role: savvyaxl.email

