---
- name: Update Red Hat and Fedora
  hosts: "{{ my_hosts | default ('update') }}"
  become: false
  remote_user: ansible
  gather_facts: true
  order: sorted
  vars:
    myhosts: linux
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  pre_tasks:
    - name: j2 summery
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_linux/templates/summery_fail.j2
        dest: "/{{temp_dir}}/summery.{{inventory_hostname}}.html"

  post_tasks:
    - name: Use j2 template to create individual body part
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_linux/templates/body.j2
        dest: "/{{temp_dir}}/body.{{inventory_hostname}}.html"

    - name: j2 summery
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_linux/templates/summery.j2
        dest: "/{{temp_dir}}/summery.{{inventory_hostname}}.html"

  roles:
    - role: savvyaxl.update_linux

