---
- name: Update Red Hat and Fedora
  hosts: "{{ my_hosts | default ('update') }}"
  become: false
  remote_user: ansible
  gather_facts: false
  order: sorted
  vars:
    myhosts: linux
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  # pre_tasks:
  #   - name: get the start time
  #     run_once: true
  #     delegate_to: localhost
  #     register: time_start_linux
  #     shell: date

  #   - name: write role start time to file
  #     run_once: true
  #     delegate_to: localhost
  #     ansible.builtin.lineinfile:
  #       line: "time_start_linux: \"{{time_start_linux.stdout}}\""
  #       path: "{{temp_file}}"
  #       create: true

  post_tasks:
    # - name: get the end time
    #   run_once: true
    #   delegate_to: localhost
    #   register: time_end_linux
    #   shell: date

    # - name: write end time to file
    #   delegate_to: localhost
    #   run_once: true
    #   ansible.builtin.lineinfile:
    #     line: "time_end_linux: \"{{time_end_linux.stdout}}\""
    #     path: "{{temp_file}}"

    - name: Use j2 template to create individual body part
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_linux/templates/body.j2
        dest: "/{{temp_dir}}/body.{{inventory_hostname}}.html"

    - name: j2 summery
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_linux/templates/summery.j2
        dest: "/{{temp_dir}}/summery.{{inventory_hostname}}.html"

  roles:
    - role: savvyaxl.update_linux

