---
- name: Update Windows
  hosts: "{{ my_win_hosts | default ('windows') }}"
  gather_facts: false
  forks: 1
  vars:
    myhosts: windows
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  pre_tasks:
    - name: j2 summery
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_windows/templates/summery_fail.j2
        dest: "{{temp_dir}}/summery.{{inventory_hostname}}.html"

  post_tasks:
    - name: Use j2 template to create individual body part
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_windows/templates/body.j2
        dest: "{{temp_dir}}/body.{{inventory_hostname}}.html"

    - name: j2 summery
      delegate_to: localhost
      ansible.builtin.template:
        src: savvyaxl.update_windows/templates/summery.j2
        dest: "{{temp_dir}}/summery.{{inventory_hostname}}.html"


  roles:
    - role: savvyaxl.update_windows

