---
- name: Update Windows
  hosts: "{{ my_win_hosts | default ('windows') }}"
  gather_facts: false
  serial: 1
  vars:
    temp_dir: /tmp/hsuteo_email
    temp_file: "{{temp_dir}}/file"

  pre_tasks:
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "{{temp_file}}"
        line: "{{inventory_hostname}}"

  roles:
    - role: savvyaxl.update_windows

