---
# tasks file for savvyaxl.updade_windows
- name: Check value for RebootPending
  register: rebootpending
  ansible.windows.win_powershell: Test-Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending'
  
- name: Reboot if RebootPending value is True
  when: rebootpending.stdout.find("True") != -1
  ansible.windows.win_reboot: 

- name: update
  become: true
  become_method: runas
  become_user: SYSTEM
  register: win_update
  ansible.windows.win_updates:
    category_names: '*'
    reject_list:
    - Lenovo - Input - USB Enhanced Performance Keyboard
    reboot: false
  ignore_errors: true

- name: Initialize rebooted
  ansible.builtin.set_fact:
    win_reboot:
      rebooted: false

- name: Reboot the machine with all defaults
  register: win_reboot
  when: do_reboot and win_update.reboot_required
  ansible.windows.win_reboot:

- name: Windows up time
  register: uptime
  ansible.windows.win_powershell:
    script: |
      $current = (Get-CimInstance -ClassName Win32_OperatingSystem -Property LastBootUpTime).LastBootUpTime
      $end= Get-Date
      $diff= New-TimeSpan -Start $current -End $end
      Write-Output "Uptime: $diff"

- name: Debug
  ansible.builtin.debug:
    var: win_update
