---
# tasks file for savvyaxl.email
# I will need the following.
# j2 template, body.j2
# tmp4_file that was created by the summary
# job start and end time

# - name: Create the body and add summery file
#   run_once: True
#   delegate_to: "{{delegation}}"
#   ansible.builtin.shell: cat {{ tmp4_file }} >> {{mail_body_file}}

# - name: Start and End time
#   delegate_to: "{{delegation}}"
#   run_once: True
#   ansible.builtin.shell: |
#     echo "<p>Start: {{ start_date.stdout | default(omit) }}</p>" >> {{ mail_body_file }}
#     echo "<p>End: {{ end_date.stdout | default(omit) }}</p>" >> {{ mail_body_file }}


- name: add the individual runs
  delegate_to: "{{delegation}}"
  run_once: True
  ansible.builtin.shell: |
    for x in {{temp_dir}}/body.*.html
    do
    cat ${x}  >> {{mail_body_file}}
    done

- name: get the mail body to variable
  register: mail_body
  delegate_to: "{{delegation}}"
  run_once: True
  ansible.builtin.command: "cat {{mail_body_file}}"

- name: Sending an e-mail using gmail with app key
  delegate_to: "{{delegation}}"
  run_once: True
  register: emailresult
  until: emailresult is not failed
  retries: 3
  delay: 20
  community.general.mail:
    host: "{{ gmail.host }}"
    port: "{{ gmail.port }}"
    username: "{{ gmail.username  | default(omit) }}"
    password: "{{ gmail.password  | default(omit) }}"
    subtype: html
    to: "{{ updateAll.to }}"
    from: "{{ updateAll.from }}"
    subject: Ansible-report for {{start_date.stdout}}
    #body: "{{my_new_fact}}"
    body: "{{mail_body.stdout | default(' ') }}"
    #secure: "{{ gmail.secure }}"
