---
- name: summery is a table
  delegate_to: "{{delegation}}"
  run_once: True
  ansible.builtin.shell: |
    echo "<table>" >> {{mail_body_file}}

- name: add the summery runs
  delegate_to: "{{delegation}}"
  run_once: True
  ansible.builtin.shell: |
    for x in {{temp_dir}}/summery.*.html
    do
    cat ${x}  >> {{mail_body_file}}
    done

- name: summery is a table
  delegate_to: "{{delegation}}"
  run_once: True
  ansible.builtin.shell: |
    echo "</table>" >> {{mail_body_file}}

- name: add the individual runs
  delegate_to: "{{delegation}}"
  run_once: True
  ansible.builtin.shell: |
    for x in {{temp_dir}}/body.*.html
    do
    cat ${x}  >> {{mail_body_file}}
    done

- name: get the mail body to variable
  register: mail_body
  delegate_to: "{{delegation}}"
  run_once: True
  ansible.builtin.command: "cat {{mail_body_file}}"

- name: Sending an e-mail using gmail with app key
  delegate_to: "{{delegation}}"
  run_once: True
  register: emailresult
  until: emailresult is not failed
  retries: 3
  delay: 20
  community.general.mail:
    host: "{{ gmail.host }}"
    port: "{{ gmail.port }}"
    username: "{{ gmail.username  | default(omit) }}"
    password: "{{ gmail.password  | default(omit) }}"
    subtype: html
    to: "{{ updateAll.to }}"
    from: "{{ updateAll.from }}"
    subject: Ansible-report for {{ subject_name  | default("updates") }}
    body: "{{mail_body.stdout | default(' ') }}"
    #secure: "{{ gmail.secure }}"
