- name: create response file
  ansible.builtin.template:
    src: response.j2
    dest: "/tmp/response"

- name: create JVM
  ignore_errors: true
  ansible.builtin.shell: |
    /opt/IBM/WebSphere/AppServer/bin/manageprofiles.sh \
    -response /tmp/response

