---
- name: Get timestamp from the system
  shell: "date"
  register: start_date
  delegate_to: "{{delegation}}"
  run_once: true
  become: false

- name: Create the start file
  shell: "echo {{ inventory_hostname }} >> {{ start_file }}"
  delegate_to: "{{delegation}}"
  become: false

- name: Update all installed packages using YUM module
  become: true
  register: yum_updates
  yum:
    name: '*'
    state: latest
    update_cache: yes
    update_only: yes

- name: Create the connected file
  shell: "echo {{ inventory_hostname }} >> {{ connected_file }}"
  delegate_to: "{{delegation}}"
  become: false

- name: Create the updated file
  shell: "echo {{ inventory_hostname }} >> {{ updated_file }}"
  delegate_to: "{{delegation}}"
  when: yum_updates.changed
  become: false

- name: check to see if we need a reboot
  become: true
  command: needs-restarting -r
  register: needsrestart
  changed_when: needsrestart.rc == 1
  notify:
    - Perform reboot
    - Wait for 200 seconds after the reboot

- name: Create the needsrestart file
  shell: "echo {{ inventory_hostname }} >> {{ needsrestart_file }}"
  delegate_to: "{{delegation}}"
  when: needsrestart.rc == 1
  become: false

- name: Flush handlers
  meta: flush_handlers

- name: Get the uptime
  command: uptime
  register: uptime

- name: check to see if we need a reboot the second time
  become: true
  command: needs-restarting -r
  register: needsrestart2
  ignore_errors: yes

- name: Create the Restarted file
  shell: "echo {{ inventory_hostname }} >> {{ restared_file }}"
  delegate_to: "{{delegation}}"
  when: needsrestart2.rc == 0 and needsrestart.rc == 1
  become: false

- name: Get timestamp from the system
  shell: "date"
  register: end_date
  delegate_to: "{{delegation}}"
  run_once: true
  become: false


- include_tasks: create_summery.yml

- include_tasks: email.yml

- include_tasks: clear_files.yml
